// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microservice.Persistence.EFCore.Data.Entities;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using System;

namespace Microservice.Persistence.EFCore.Data.Contexts
{
    public class OrderConfiguration : IEntityTypeConfiguration<Order>
    {
        public void Configure(EntityTypeBuilder<Order> entity)
        {
            entity.ToTable("Order");

            entity.Property(e => e.Description)
                .HasMaxLength(250)
                .IsUnicode(false);
        }
    }
}
