// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microservice.Persistence.EFCore.Data.Entities;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using System;

namespace Microservice.Persistence.EFCore.Data.Contexts
{
    public class ProductConfiguration : IEntityTypeConfiguration<Product>
    {
        public void Configure(EntityTypeBuilder<Product> entity)
        {
            entity.ToTable("Product");

            entity.Property(e => e.Description)
                .HasMaxLength(250)
                .IsUnicode(false);

            entity.Property(e => e.Price).HasColumnType("decimal(30, 6)");

            entity.Property(e => e.Unit)
                .HasMaxLength(3)
                .IsUnicode(false);
        }
    }
}
