#See https://aka.ms/containerfastmode to understand how Visual Studio uses this Dockerfile to build your images for faster debugging.

FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src
COPY ["Microservices.Monitoring.Client.MVC.csproj", "./"]
RUN dotnet restore "Microservices.Monitoring.Client.MVC.csproj"
COPY . .
WORKDIR /src
RUN dotnet build "Microservices.Monitoring.Client.MVC.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "Microservices.Monitoring.Client.MVC.csproj" -c Release -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "Microservices.Monitoring.Client.MVC.dll"]