version: '3.4'

services:
########################################################## Rabbitmq ####################################################################################
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - 15691:15691
      - 15692:15692
      - 15672:15672
      - 15671:15671
      - 35197:35197
      - 4369:4369
      - 55672:55672
      - 5672:5672
      - 5671:5671
      - 25672:25672
    environment:
      - RABBITMQ_DEFAULT_USER=test
      - RABBITMQ_DEFAULT_PASS=test    
    networks:
      - backend
########################################################## networks #######################################################################################################
networks:
  backend:
    name: backend
    driver: bridge

