// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Microservice.CQRS.Premium.Infrastructure.Entities
{
    public partial class Match
    {
        public string Id { get; set; }
        public string Team1 { get; set; }
        public string Team2 { get; set; }
        public int State { get; set; }
        public int Score1 { get; set; }
        public int Score2 { get; set; }
        public int Period { get; set; }
        public string Timeouts1 { get; set; }
        public string Timeouts2 { get; set; }
    }
}