#See https://aka.ms/containerfastmode to understand how Visual Studio uses this Dockerfile to build your images for faster debugging.

FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
WORKDIR /app
EXPOSE 8080
EXPOSE 443

FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src
COPY ["Microservices.Resilient.Hystrix.API/Microservices.Resilient.Hystrix.API.csproj", "Microservices.Resilient.Hystrix.API/"]
RUN dotnet restore "Microservices.Resilient.Hystrix.API/Microservices.Resilient.Hystrix.API.csproj"
COPY . .
WORKDIR "/src/Microservices.Resilient.Hystrix.API"
RUN dotnet build "Microservices.Resilient.Hystrix.API.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "Microservices.Resilient.Hystrix.API.csproj" -c Release -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "Microservices.Resilient.Hystrix.API.dll"]