apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: hello-world
  name: hello-world
  namespace: develop
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hello-world    
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      containers:
      - name: hello-app
        image: gcr.io/google-samples/hello-app:1.0
