// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microservices.Monitoring.Sales.API.Infrastructure.Data.Entities;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using System;

namespace Microservices.Monitoring.Sales.API.Infrastructure.Data.Contexts
{
    public class OrderItemConfiguration : IEntityTypeConfiguration<OrderItem>
    {
        public void Configure(EntityTypeBuilder<OrderItem> entity)
        {
            entity.HasKey(e => new { e.OrderId, e.OrderItemId })
                .HasName("PK__OrderIte__C6EE8BA7234DBF9F");

            entity.ToTable("OrderItem", "Sales");

            entity.Property(e => e.Discount).HasColumnType("decimal(4, 2)");

            entity.Property(e => e.ListPrice).HasColumnType("decimal(10, 2)");

            entity.HasOne(d => d.Order)
                .WithMany(p => p.OrderItems)
                .HasForeignKey(d => d.OrderId)
                .HasConstraintName("FK__OrderItem__Order__3B75D760");

            entity.HasOne(d => d.Product)
                .WithMany(p => p.OrderItems)
                .HasForeignKey(d => d.ProductId)
                .HasConstraintName("FK__OrderItem__Produ__3C69FB99");
        }
    }
}
