// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microservices.Monitoring.Products.API.Infrastructure.Data.Entities;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using System;

namespace Microservices.Monitoring.Products.API.Infrastructure.Data.Contexts
{
    public class StockConfiguration : IEntityTypeConfiguration<Stock>
    {
        public void Configure(EntityTypeBuilder<Stock> entity)
        {
            entity.HasKey(e => new { e.StoreId, e.ProductId })
                .HasName("PK__Stock__F0C23D6DF3C2EDB1");

            entity.ToTable("Stock", "Products");

            entity.HasOne(d => d.Product)
                .WithMany(p => p.Stocks)
                .HasForeignKey(d => d.ProductId)
                .HasConstraintName("FK__Stock__ProductId__35BCFE0A");

            entity.HasOne(d => d.Store)
                .WithMany(p => p.Stocks)
                .HasForeignKey(d => d.StoreId)
                .HasConstraintName("FK__Stock__StoreId__36B12243");
        }
    }
}
