services:
  ########################################################## Client Angular ###############################################################################
  microservices.apigateway.client.angular:
    container_name: microservices.apigateway.client.angular
    image: microservices.apigateway.client.angular
    build:
      context: microservices.apigateway.client.angular
      dockerfile: Dockerfile    
    ports:
      - 8081:80    
    networks:
      - backend   
  ########################################################## Products API #################################################################################
  microservices.apigateway.product.api:
    container_name: microservices.apigateway.product.api
    image: microservices.apigateway.product.api
    build:
      context: microservices.apigateway.product.api
      dockerfile: Dockerfile    
    ports:
      - 8083:8080
      - 8084:443
    networks:
      - backend    
  ########################################################## Sales API ####################################################################################
  microservices.apigateway.sale.api:
    container_name: microservices.apigateway.sale.api
    image: microservices.apigateway.sale.api
    build:
      context: microservices.apigateway.sale.api
      dockerfile: Dockerfile    
    ports:
      - 8085:8080
      - 8086:443
    networks:
      - backend    
########################################################## Network ##################################################################################
networks:
  backend:    
    driver: bridge