services:
  ########################################################## Client Angular ###############################################################################
  microservices.apigateway.client.angular:
    container_name: microservices.apigateway.client.angular
    image: scorpius8/microservices.apigateway.client.angular
    build:
      context: microservices.apigateway.client.angular
      dockerfile: Dockerfile    
    ports:
      - 8081:8080
    networks:
      - backend   
  ########################################################## Products API #################################################################################
  microservices.apigateway.product.api:
    #container_name: microservices.apigateway.product.api
    deploy:
      replicas: 3
    image: scorpius8/microservices.apigateway.product.api
    build:
      context: microservices.apigateway.product.api
      dockerfile: Dockerfile    
    #ports:
      #- 8083:8080
      #- 8084:443
    networks:
      - backend    
  ########################################################## Sales API ####################################################################################
  microservices.apigateway.sale.api:
    #container_name: microservices.apigateway.sale.api
    deploy:
      replicas: 3
    image: scorpius8/microservices.apigateway.sale.api
    build:
      context: microservices.apigateway.sale.api
      dockerfile: Dockerfile    
    #ports:
    #  - 8085:8080
    #  - 8086:443
    networks:
      - backend
  ########################################################## API Gateway ####################################################################################
  microservices.apigateway.ocelot:
    container_name: microservices.apigateway.ocelot
    image: scorpius8/microservices.apigateway.ocelot
    build:
      context: microservices.apigateway.ocelot
      dockerfile: Dockerfile    
    ports:
      - 8087:8080
      - 8088:443
    networks:
      - backend
  ########################################################## Auth API ####################################################################################
  microservices.apigateway.auth.api:
    container_name: microservices.apigateway.auth.api
    image: scorpius8/microservices.apigateway.auth.api
    build:
      context: microservices.apigateway.auth.api
      dockerfile: Dockerfile    
    ports:
      - 8089:8080
      - 8090:443
    networks:
      - backend
  ########################################################## Discovery Server ##################################################################################
  microservices.apigateway.discoveryservice:
    container_name: microservices.apigateway.discoveryservice
    image: scorpius8/microservices.apigateway.discoveryservice
    build:
      context: microservices.apigateway.discoveryservice
      dockerfile: Dockerfile
    ports:
      - 8761:8761
    networks:
      - backend
########################################################## Network ##################################################################################
networks:
  backend:    
    driver: bridge