version: '3.4'

services:
  microservices.resilient.hystrix.api:
    container_name: microservices.resilient.hystrix.api
    image: microservices.resilient.hystrix.api
    build:
      context: .
      dockerfile: Microservices.Resilient.Hystrix.API/Dockerfile
    ports:
      - 8081:8080
      - 8082:443
    networks:
      - backend  
  microservices.resilient.hystrix.client.mvc:
    container_name: microservices.resilient.hystrix.client.mvc
    image: ${DOCKER_REGISTRY-}microservicesresilienthystrixclientmvc
    build:
      context: .
      dockerfile: Microservices.Resilient.Hystrix.Client.MVC/Dockerfile
    ports:
      - 8083:8080
      - 8084:443
    networks:
      - backend
  microservices.resilient.hystrix.dashboard:
    container_name: microservices.resilient.hystrix.dashboard
    image: microservices.resilient.hystrix.dashboard
    build:
      context: Microservices.Resilient.Hystrix.Dashboard
      dockerfile: Dockerfile
    ports:
      - 7979:7979
    networks:
      - backend
  rabbitmq:
    image: rabbitmq:3.13.1-management
    ports:
      - 15672:15672
      - 5672:5672
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest    
    networks:
      - backend
networks:
  backend:
    name: backend
    driver: bridge
