services:
######################################################################### elastic search ##################################################################################
##http://localhost:9200/_cat/nodes?v=true&pretty
##http://localhost:9200/_cluster/health?pretty
  elasticsearch:
    container_name: es01-test
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.4
    ports:
      - 9200:9200 
      - 9300:9300
    environment:
      - ELASTIC_PASSWORD=elastic      
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ulimits:
      memlock:
        hard: -1
        soft: -1    
    volumes:
      - ./elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - ./elasticsearch/es-data:/usr/share/elasticsearch/data
    networks:
      - backend  
################################################################################# kibana ##################################################################################      
  kibana:
    container_name: kib01-test
    image: docker.elastic.co/kibana/kibana:8.13.4    
    volumes:
      - ./kibana/kibana.yml:/usr/share/kibana/config/kibana.yml
    ports:      
      - 5601:5601
    networks:
      - backend
    depends_on:
      - elasticsearch    
######################################################################### logstash ##################################################################################
  logstash:
    container_name: ls01-test
    image: docker.elastic.co/logstash/logstash:8.13.4
    ports:
      - 5044:5044
      - 28080:28080
    volumes:
      - ./logstash/logstash.yml:/usr/share/logstash/config/logstash.yml
      - ./logstash/conf.d/:/usr/share/logstash/pipeline/:ro
    networks:
      - backend
    depends_on:
      - elasticsearch
    restart: on-failure
######################################################################### APM ##################################################################################
  apm-server:
    container_name: apm-server
    image: docker.elastic.co/apm/apm-server:8.13.4    
    ports:
      - 8200:8200      
    volumes:
      - ./apm/apm-server.yml:/usr/share/apm-server/apm-server.yml:ro"
    networks:
      - backend    
    depends_on:
      - elasticsearch
    restart: on-failure
########################################################## networks #######################################################################################################
networks:
  backend:
    name: backend
    driver: bridge