services:
######################################################################### elastic search ##################################################################################
##http://localhost:9200/_cat/nodes?v=true&pretty
##http://localhost:9200/_cluster/health?pretty
  elasticsearch:
    container_name: es01-test
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.4
    ports:
      - 9200:9200 
      - 9300:9300
    environment:
      - ELASTIC_PASSWORD=elastic      
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ulimits:
      memlock:
        hard: -1
        soft: -1    
    volumes:
      - ./elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - ./elasticsearch/es-data:/usr/share/elasticsearch/data
    networks:
      - backend  
########################################################## networks #######################################################################################################
networks:
  backend:
    name: backend
    driver: bridge