services:
################################################################################# kibana ##################################################################################      
  kibana:
    container_name: kib01-test
    image: docker.elastic.co/kibana/kibana:8.13.4
    volumes:
      - ./kibana/kibana.yml:/usr/share/kibana/config/kibana.yml
    ports:      
      - 5601:5601
    networks:
      - backend
########################################################## networks #######################################################################################################
networks:
  backend:
    name: backend
    driver: bridge