// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microservice.CQRS.Premium.Infrastructure.Entities;
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

namespace Microservice.CQRS.Premium.Infrastructure.Context
{
    public partial class MicroserviceCQRSContext : DbContext
    {
        public MicroserviceCQRSContext()
        {
        }

        public MicroserviceCQRSContext(DbContextOptions<MicroserviceCQRSContext> options)
            : base(options)
        {
        }

        public virtual DbSet<Match> Matches { get; set; }
        public virtual DbSet<MatchEvent> MatchEvents { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            if (!optionsBuilder.IsConfigured)
            {
            }
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.HasAnnotation("ProductVersion", "2.2.0-rtm-35687");

            modelBuilder.Entity<Match>(entity =>
            {
                entity.Property(e => e.Id)
                    .HasMaxLength(128)
                    .ValueGeneratedNever();
            });

            modelBuilder.Entity<MatchEvent>(entity =>
            {
                entity.Property(e => e.Action)
                    .IsRequired()
                    .HasMaxLength(50);

                entity.Property(e => e.MatchId)
                    .IsRequired()
                    .HasMaxLength(10);

                entity.Property(e => e.Team1).HasMaxLength(50);

                entity.Property(e => e.Team2).HasMaxLength(50);

                entity.Property(e => e.TimeStamp).HasColumnType("datetime");
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}