version: '3.4'

services:      
  mssql:
    container_name: mssql
    image: "mcr.microsoft.com/mssql/server"
    environment:
        SA_PASSWORD: "Password1234"
        ACCEPT_EULA: "Y"
    ports:
     - '1433:1433'
    networks:
    - netmicroservicescleanarchitecturedev
networks:
  netmicroservicescleanarchitecturedev:
    external: false
    name: netmicroservicescleanarchitecturedev