version: '3.4'

services:
  netmicroservicescleanarchitecture.app:    
    image: ${DOCKER_REGISTRY-}netmicroservicescleanarchitecture-app
    build:
      context: Source
      dockerfile: Presentation/Net.Microservices.CleanArchitecture.Presentation.Web/Dockerfile
    ports:
      - '8001:80'
    environment:
      - ASPNETCORE_ENVIRONMENT=DockerCompose
    depends_on:
      - mssql
    networks:
      - netmicroservicescleanarchitecturedev
    restart: on-failure
  mssql:
    container_name: mssql
    image: "mcr.microsoft.com/mssql/server"
    environment:
      SA_PASSWORD: "Password1234"
      ACCEPT_EULA: "Y"
    ports:
      - '1433:1433'
    networks:
      - netmicroservicescleanarchitecturedev
networks:
  netmicroservicescleanarchitecturedev:
    external: false
    name: netmicroservicescleanarchitecturedev