version: '3.4'

services:
########################################################## microservices.demo.policy.db ##################################################################################
  sqlserver2019:
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - 1433:1433 
    environment:
      - SA_PASSWORD=Password1234
      - ACCEPT_EULA=Y
    networks:
      - backend
########################################################## microservices.demo.policy.db ##################################################################################
  redisserver:
    image: redis
    ports:
      - 6379:6379    
    networks:
      - backend
########################################################## microservices.demo.policy.db ##################################################################################
  mongodb:
    image: mongo
    ports:
      - 27017:27017      
    networks:
      - backend
########################################################## microservices.demo.policy.db ##################################################################################
  eventstoreserver:
    image: eventstore/eventstore:latest
    ports:
      - 2113:2113
      - 2112:2112
      - 1113:1113
      - 1112:1112
    environment:
      - EVENTSTORE_CLUSTER_SIZE=1
      - EVENTSTORE_RUN_PROJECTIONS=All
      - EVENTSTORE_START_STANDARD_PROJECTIONS=true
      - EVENTSTORE_EXT_TCP_PORT=1113
      - EVENTSTORE_EXT_HTTP_PORT=2113
      - EVENTSTORE_INSECURE=true
      - EVENTSTORE_ENABLE_EXTERNAL_TCP=true
      - EVENTSTORE_ENABLE_ATOM_PUB_OVER_HTTP=true
    networks:
      - backend
########################################################## microservices.demo.rabbitmq ####################################################################################
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - 15691:15691
      - 15692:15692
      - 15672:15672
      - 15671:15671
      - 35197:35197
      - 4369:4369
      - 55672:55672
      - 5672:5672
      - 5671:5671
      - 25672:25672
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest    
    networks:
      - backend
########################################################## networks #######################################################################################################
networks:
  backend:
    name: backend
    driver: bridge

