version: '3.4'

services:
########################################################## Redis Server ##################################################################################
  redisserver:
    image: redis:7.2.4
    ports:
      - 6379:6379    
    networks:
      - backend
########################################################## Event Store Server ##################################################################################
#  eventstoreserver:
#    image: eventstore/eventstore:24.2
#    ports:
#      - 2113:2113
#      - 1113:1113
#    command: --insecure --run-projections=All  --enable-atom-pub-over-http
#    networks:
#      - backend
  eventstoreserver:
    image: eventstore/eventstore:20.10.5-buster-slim
#    image: eventstore/eventstore:24.2
    ports:
      - 2113:2113
      - 2112:2112
      - 1113:1113
      - 1112:1112
    environment:
      - EVENTSTORE_CLUSTER_SIZE=1
      - EVENTSTORE_RUN_PROJECTIONS=All
      - EVENTSTORE_START_STANDARD_PROJECTIONS=true
      - EVENTSTORE_EXT_TCP_PORT=1113
      - EVENTSTORE_EXT_HTTP_PORT=2113
      - EVENTSTORE_INSECURE=true
      - EVENTSTORE_ENABLE_EXTERNAL_TCP=true
      - EVENTSTORE_ENABLE_ATOM_PUB_OVER_HTTP=true
    networks:
      - backend
########################################################## Rabbitmq ####################################################################################
  rabbitmq:
    image: rabbitmq:3.13.1-management
    ports:
      - 15672:15672
      - 5672:5672
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest    
    networks:
      - backend
########################################################## redisinsight ####################################################################################
  redisinsight:
    image: redislabs/redisinsight:1.14.0
    ports:
      - "8001:8001"
    networks:
      - backend
########################################################## networks #######################################################################################################
networks:
  backend:
    name: backend
    driver: bridge

