// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Microservice.CQRS.Deluxe.Infrastructure.Persistence.SqlServer.Data.Entities
{
    public partial class Court
    {
        public Court()
        {
            Bookings = new HashSet<Booking>();
        }

        public int Id { get; set; }
        public string Name { get; set; }
        public int FirstSlot { get; set; }
        public int LastSlot { get; set; }

        public virtual ICollection<Booking> Bookings { get; set; }
    }
}