// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microservice.CQRS.Deluxe.Infrastructure.Extras.Backend.Entities;
using System;
using Microsoft.EntityFrameworkCore;

namespace Microservice.CQRS.Deluxe.Infrastructure.Extras.Backend.Context
{
    public partial class MerloXtraContext : DbContext
    {
        public MerloXtraContext()
        {
        }

        public MerloXtraContext(DbContextOptions<MerloXtraContext> options)
            : base(options)
        {
        }

        public virtual DbSet<SentEmail> SentEmails { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            if (!optionsBuilder.IsConfigured)
            {
            }
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.HasAnnotation("ProductVersion", "2.2.0-rtm-35687");

            modelBuilder.Entity<SentEmail>(entity =>
            {
                entity.Property(e => e.Address)
                    .IsRequired()
                    .HasMaxLength(50);

                entity.Property(e => e.Body)
                    .IsRequired()
                    .HasMaxLength(200);

                entity.Property(e => e.Sent).HasColumnType("datetime");
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}