// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microservice.CQRS.Deluxe.Infrastructure.EventStore.SqlServer.Data.Entities;
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

namespace Microservice.CQRS.Deluxe.Infrastructure.EventStore.SqlServer.Data.Context
{
    public partial class MerloEventStoreContext : DbContext
    {
        public MerloEventStoreContext()
        {
        }

        public MerloEventStoreContext(DbContextOptions<MerloEventStoreContext> options)
            : base(options)
        {
        }

        public virtual DbSet<LoggedEvent> LoggedEvents { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            if (!optionsBuilder.IsConfigured)
            {
            }
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.HasAnnotation("ProductVersion", "2.2.0-rtm-35687");

            modelBuilder.Entity<LoggedEvent>(entity =>
            {
                entity.Property(e => e.Action)
                    .IsRequired()
                    .HasMaxLength(50);

                entity.Property(e => e.TimeStamp).HasColumnType("datetime");
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}