---
######################################### Cross ########################################
#- name: Load result kubeadm join
#  shell: cat roles/node/files/kubeadm_join_cmd.txt | sed -e "s/10.0.1.10/{{ansible_eth0.ipv4.address}}/"
#  register: kubeadm_join_cmd
#  delegate_to: localhost
  
- name: Load result kubeadm join
  shell: cat roles/node/files/kubeadm_join_cmd.txt
  register: kubeadm_join_cmd
  delegate_to: localhost

- name: Join node
  shell: "{{kubeadm_join_cmd.stdout}} --ignore-preflight-errors=swap"