version: '3.7'

services: 
    generator:
        build: 
            context: .
        image: acrmicroserviceseac.azurecr.io/generator:1.0.0.1
        ports: 
            - "8085:8080"
    mail:
        image: mailhog/mailhog
        ports: 
            - "8025:8025"
            - "1025:1025"