// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Microservice.CQRS.Deluxe.Infrastructure.Extras.Backend.Entities
{
    public partial class SentEmail
    {
        public int Id { get; set; }
        public string Address { get; set; }
        public string Body { get; set; }
        public DateTime Sent { get; set; }
    }
}