version: '3.4'

services:
  validator.service:
    image: ${DOCKER_REGISTRY-}microservicesvalidatorservice
    build:
      context: .
      dockerfile: Microservices.Validator.Service/Dockerfile
    networks:
      - saga-network
  mongodb:
    image: mongo:7.0.8
    container_name: mongodb
    ports:
      - 27017:27017      
    networks:
      - saga-network
  kafka:
    image: 'bitnami/kafka:3.6.2'
    container_name: kafka
    environment:
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://0.0.0.0:9094
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,EXTERNAL://localhost:9094
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT      
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
    ports:
      - 9092:9092
      - 9094:9094
    networks:
      - saga-network
  kafka-ui:
    container_name: kafka-ui
    image: provectuslabs/kafka-ui:v0.7.2
    ports:
      - 8081:8080    
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092      
    networks:
      - saga-network
networks:
  saga-network:
    driver: bridge
    name: saga-network
