version: '3.4'

services:
########################################################## SQL Server ##################################################################################
  sqlserver2022:
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
       - 1434:1433 
    environment:
      - SA_PASSWORD=Password1234
      - ACCEPT_EULA=Y
    networks:
      - backend
########################################################## networks ####################################################################################
networks:
  backend:
    name: backend
    driver: bridge

