// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Microservices.Monitoring.Products.API.Infrastructure.Data.Entities
{
    public partial class staff
    {
        public staff()
        {
            InverseManager = new HashSet<staff>();
            Orders = new HashSet<Order>();
        }

        public int StaffId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public byte Active { get; set; }
        public int StoreId { get; set; }
        public int? ManagerId { get; set; }

        public virtual staff Manager { get; set; }
        public virtual Store Store { get; set; }
        public virtual ICollection<staff> InverseManager { get; set; }
        public virtual ICollection<Order> Orders { get; set; }
    }
}