Vagrant.configure("2") do |config|
  config.vm.box = "generic/ubuntu2004"
  config.vm.provider "hyperv"
  config.vm.hostname = "k8s-node02"
  config.vm.network "public_network", bridge: "External Switch"
  
  config.vm.provider "hyperv" do |p|
  	p.memory = "2048"
  	p.cpus = "2"
  	p.vmname = "k8s-node02"
  end
  
  config.vm.provision :shell, path: "configure-static-ip.sh", run: 'always', reboot:true
  config.vm.provision :shell, path: "configure-prerequisites-k8s.sh", run: 'always'  
  config.vm.provision :shell, path: "configure-node.sh", run: 'always'   
end
